[package]
name = "aoo"
version = "0.1.0"
edition = "2021"
authors = ["Joseph <joseph1666888.gmail.com>"]
repository = "https://github.com/ikeaper/aoo"
license = "MIT"

[dependencies]

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
